.\" Manpage for easymake

.TH man 1 "14 January 2021" "1.0" "easymake manpage"
.SH NAME
easymake \- Simple GNU Make or CMake alternative.
.SH SYNOPSIS
easymake [OPTIONS] [TARGET]
.SH DESCRIPTION
Easymake is a full replacement for GNU Make or CMake.
.SH OPTIONS
-h / --help - Display the help page.

-v / --version - Display version information

-f / --file - Specify a build file. If one is not specified, 'Build' will be used by default.

-d / --debug - Enable verbose output

.SH BUGS
No known bugs.
.SH AUTHOR
Fossbay
